### ISSUE TITLE
Why not print the exception info by console?

### ISSUE THREAD

**Issue by jstzwj** [dotnetGame/MineCase#10]
https://github.com/dotnetGame/MineCase/blob/fc589b6c4e9cb20b7b73374fb9568903cb683939/src/MineCase.Gateway/Network/ConnectionRouter.cs#L47

**Comment by sunnycase** [comment]
Sure. Use `_logger.LogError` report it.

**Comment by jstzwj** [comment]
Solved in [#13](https://github.com/dotnetGame/MineCase/pull/13)
