### ISSUE TITLE
I did not see the game interface

### ISSUE THREAD

**Issue by csoftware** [dotnetGame/MineCase#104]
This is a server-side source does not have a client right

**Comment by jstzwj** [comment]
MineCase is a minecraft-compatible server. There is a quite simple client in source which only draws the chunks sent from server.  The directory ‘MineCase/src/MineCase.Client/’ can be opened in unity.

**Comment by jstzwj** [comment]
After starting the server from source， you can see the console as shown below.
![minecase_capture](https://user-images.githubusercontent.com/13167278/33470871-8060fe38-d6a5-11e7-83c8-1a0de15d1c35.png)

I can't tell what happened and need more details.

**Comment by csoftware** [comment]
Thank you for answering
I study it, but still suggest a complete client case, so it's better to understand orleans

**Comment by jstzwj** [comment]
The gateway in source is the grain client of grains.
[https://github.com/dotnetGame/MineCase/tree/master/src/MineCase.Gateway](https://github.com/dotnetGame/MineCase/tree/master/src/MineCase.Gateway)
It connects to cluster and serves for Minecraft client.

**Comment by csoftware** [comment]
ok, thank you
