### ISSUE TITLE
There is a mistake with the file name

### ISSUE THREAD

**Issue by jstzwj** [dotnetGame/MineCase#11]
https://github.com/dotnetGame/MineCase/blob/master/src/MineCase.Server.Interfaces/Game/LevelTYpes.cs

**Comment by sunnycase** [comment]
Solved in #12.

**Comment by sunnycase** [comment]
Solved in #12.

**Comment by jstzwj** [comment]
Solved in [](https://github.com/dotnetGame/MineCase/pull/12)
