### ISSUE TITLE
Consider using the same plugin architecture as JungleTree

### ISSUE THREAD

**Issue by yangm97** [dotnetGame/MineCase#120]
[JungleTree](https://github.com/JungleTree/JungleTree) is another project planning to implement distributed minecraft servers. It has started drafting a plugin API and I think it would be better if both projects agreed on using the same API, collaboration, sharing work, community, something something.

**Comment by sunnycase** [comment]
Thank you for your advice. But what about simulating popular API surfaces such as Forge?

**Comment by yangm97** [comment]
It could be built on top of the plugin API. An example from JungleTree IRC channel:

![Draft](https://pbs.twimg.com/media/DSeUeOFWkAE-D7c?format=jpg)
