### ISSUE TITLE
orleans-prerelease   is not exit

### ISSUE THREAD

**Issue by bingxueyouwu** [dotnetGame/MineCase#122]
https://dotnet.myget.org/F/orleans-prerelease/api/v3/index.json   
This URL is not availabe, it shows "Feed does not exist".
Have another URL to replace it?

**Comment by erictuvesson** [comment]
I haven't worked with it, but try using https://dotnet.myget.org/F/orleans-ci/api/v3/index.json instead.

**Comment by jstzwj** [comment]
Orleans 2.0 is available now.  It should work with Orleans 2.0 from nuget.org instead of the pre-release version.

**Comment by bingxueyouwu** [comment]
I have replace it by using  " https://dotnet.myget.org/F/orleans-ci/api/v3/index.json"
