### ISSUE TITLE
About the Unity Client

### ISSUE THREAD

**Issue by XianWorld** [dotnetGame/MineCase#133]
I found there is nothing in the untiy client project, and the DLL is ignored.
What about this client, and can you remove the ignore and push the dll?

**Comment by XianWorld** [comment]
where to build client projects?
I add the client engine and scripts to the MineCase.sln, there are error for scripts peoject:

错误	NU1201	项目 MineCase.Core 与 net46 (.NETFramework,Version=v4.6) 不兼容。 项目 MineCase.Core 支持: netstandard2.0 (.NETStandard,Version=v2.0)	MineCase.Client.Scripts	D:\Projects\orleans\MineCase-master_20190823\src\MineCase.Client.Scripts\MineCase.Client.Scripts.csproj	1

**Comment by jstzwj** [comment]
MineCase Unity Client has been removed since project was updated to orleans 2.0, cuz no one would maintain it again.

**Comment by jstzwj** [comment]
I closed the issue, you can reopen it as you wish.
